### ISSUE TITLE
Custom Encodings!

### ISSUE THREAD

**Issue by theSherwood** [ccorcos/lexicodec#1]
Custom encodings! Will tuple-db end up using this this package?

**Comment by ccorcos** [comment]
Eventually... 

Could be a pretty easy refactor to get BigInts and stuff too: https://github.com/ccorcos/tuple-database/issues/25

Dealing with migrating data is always annoying but pretty simple.

I'm messing around with tuple-database right now, thinking about reworking it a bunch actually.

I like how DenoKV has explicit transactional read checks. I also really want to implement an interval tree as well... stay tuned haha

**Comment by theSherwood** [comment]
Nice. I'm using an in-memory interval tree in addition to tuple-db at the moment. I would love to be able to ditch that and have the interval-tree in tuple-database (durable).
